# Generated by Django 3.0.4 on 2020-03-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='l_name',
        ),
    ]
