# Generated by Django 3.0.4 on 2020-03-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0002_auto_20200327_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='emails',
        ),
    ]
