# Generated by Django 3.0.4 on 2020-03-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0003_auto_20200327_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
