# Generated by Django 3.0.4 on 2020-03-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_two', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, unique=True)),
                ('lname', models.CharField(max_length=100, unique=True)),
                ('emails', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
